#!/usr/bin/env bash

LAYOUT=$(hyprctl -j getoption general:layout | jq '.str' | sed 's/"//g')

case $LAYOUT in
"master")
	hyprctl keyword general:layout dwindle
	# hyprctl keyword unbind super shift, S
	# hyprctl keyword unbind super, W
	# hyprctl keyword bind super shift, S, togglesplit
	# hyprctl keyword bind super, W, pseudo
	notify-send "Layout" "Dwindle"
	;;
"dwindle")
	hyprctl keyword general:layout master
	# hyprctl keyword unbind super shift, S
	# hyprctl keyword unbind super, W
	# hyprctl keyword bind super shift, S, layoutmsg, swapwithmaster
	# hyprctl keyword bind super, W, swapnext
	notify-send "Layout" "Master"
	;;
*) ;;
esac
